as_character – Julienne
as_character Interface
199 statements
Source File
interface
Called by
private pure module function as_character(self) result(raw_string) Implementation →
Arguments
Type Intent Optional Attributes Name
class(string_t), intent(in) :: self
Return Value character(len=:),allocatable
Call graph
assign_string_t_to_character calls string
base_name calls string
character_eq_string_t calls string
character_ne_string_t calls string
characterize calls string
concatenate_elements calls string
contains_characters calls string
contains_string_t calls string
contains_text calls string
description_contains calls string
file_extension calls string
from_file_with_string_name calls string
get_double_precision calls string
get_double_precision_array calls string
get_integer calls string
get_json_key calls string
get_logical calls string
get_real calls string
get_real_array calls string
get_string calls string
string_t_eq_character calls string
string_t_eq_string_t calls string
string_t_ne_character calls string
string_t_ne_string_t calls string
write_lines calls string