name: Build with LLVM Flang

on: [push, pull_request]


jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: true
    container: gmao/llvm-flang:latest
    env:
      FC: flang-new

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: fortran-lang/setup-fpm@v6.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test with LLVM Flang
      if: contains(matrix.os, 'ubuntu')
      run: |
        fpm --version
        $FC --version
        export FPM_FC=$FC
        export FPM_FFLAGS="-mmlir -allow-assumed-rank -O3"
        fpm test
