name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-24.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: fortran-lang/setup-fpm@v6.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Dependencies on Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt install -y build-essential gfortran-14 g++-14

    - name: Install Dependencies on macOS
      if: contains(matrix.os, 'macos')
      run: |
        brew install gfortran

    - name: Build and Run unit tests
      run: |
        fpm test --compiler gfortran-14
